version: '3'

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres-data:/tmp/
    ports:
      - "5432:5432"
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  flower: # Celery Monitor
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0", "--port=8888"]  
    ports:  
      - 8888:8888  
  backend:
    image: seppaleinen/movies_backend_importer
    build: backend/importer/
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - TMDB_API=${TMDB_API}
      - SENTRY_URL=${SENTRY_URL}
  celery_worker:
    image: seppaleinen/movies_backend_importer
    depends_on:
      - db
      - backend
    entrypoint: celery -A settings.celery worker -l INFO -E --pool=gevent --autoscale=200,10
  webapp:
    image: seppaleinen/movies_webapp
    build: frontend/
    ports:
      - "80:80"
volumes:
  pgdata:
