version: '3'

services:
  db:
    image: postgres:12-alpine
  backend:
    image: seppaleinen/movies_backend_importer:dev
  webapp:
    image: seppaleinen/movies_webapp:dev
  celery_worker:
    image: seppaleinen/movies_backend_importer:dev
