# Generated by Django 2.2.3 on 2020-02-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='KeywordIds',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('fetched', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'keyword_ids',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=500)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fetched', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('imdb_id', models.TextField(db_index=True, max_length=30, null=True, unique=True)),
                ('original_language', models.TextField(blank=True, max_length=30, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, max_length=40, null=True)),
                ('release_date', models.TextField(blank=True, max_length=10, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('imdb_vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('imdb_vote_count', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='PersonIds',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fetched', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'person_ids',
            },
        ),
        migrations.CreateModel(
            name='ProductionCompanyIds',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('fetched', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'production_company_ids',
            },
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.TextField(max_length=4, unique=True)),
                ('name', models.TextField(max_length=50)),
                ('movies', models.ManyToManyField(related_name='spoken_languages', to='importer.Movie')),
            ],
        ),
        migrations.AddIndex(
            model_name='productioncompanyids',
            index=models.Index(fields=['id'], name='production_company_pk_index'),
        ),
        migrations.AddIndex(
            model_name='personids',
            index=models.Index(fields=['id'], name='person_ids_pk_index'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['id'], name='movie_pk_index'),
        ),
        migrations.AddIndex(
            model_name='keywordids',
            index=models.Index(fields=['id'], name='keyword_ids_pk_index'),
        ),
        migrations.AddField(
            model_name='genre',
            name='movies',
            field=models.ManyToManyField(related_name='genres', to='importer.Movie'),
        ),
    ]
