# Generated by Django 2.2.3 on 2020-02-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('original_title', models.CharField(max_length=500)),
                ('popularity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fetched', models.BooleanField(default=False)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('imdb_id', models.CharField(db_index=True, max_length=30, null=True, unique=True)),
                ('original_language', models.CharField(blank=True, max_length=30, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=40, null=True)),
                ('release_date', models.CharField(blank=True, max_length=10, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('imdb_vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('imdb_vote_count', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_1', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(related_name='spoken_languages', to='importer.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('movies', models.ManyToManyField(related_name='genres', to='importer.Movie')),
            ],
        ),
    ]
