# Generated by Django 3.0.3 on 2020-03-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0003_auto_20200302_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordids',
            name='movies',
            field=models.ManyToManyField(related_name='keywords', to='importer.Movie'),
        ),
        migrations.AddField(
            model_name='keywordids',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personids',
            name='movies',
            field=models.ManyToManyField(related_name='persons', to='importer.Movie'),
        ),
        migrations.AddField(
            model_name='personids',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
