name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run backend tests
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
        architecture: x64
      run: |
        pip install -r backend/importer/requirements.txt
        ./backend/importer/manage.py test
    - name: Run frontend tests
      run: |
        npm install --prefix frontend/
        npm run test --prefix frontend/
