name: CI

on: [push]

jobs:
  build-backend-importer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run backend tests
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
        architecture: x64
    - run: pip install -r backend/importer/requirements.txt
    - run: ./backend/importer/manage.py test
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install --prefix frontend/
    - name: Run tests
      run: npm run ci-test --prefix frontend/

