name: CI

on: [push]

jobs:
  build-backend-importer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python environment
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
        architecture: x64
    - name: Install dependencies
      run: pip install -r backend/importer/requirements.txt
    - name: Run tests
      run: ./backend/importer/manage.py test
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install --prefix frontend/
    - name: Run tests
      run: npm run ci-test --prefix frontend/
  integration-tests:
    runs-on: ubuntu-latest
    needs: [build-backend-importer, build-frontend]
    steps:
    - name: Pull newest docker images
      run: echo "Do stuff" 

